### ISSUE TITLE
Demo smiley face does not work?

### ISSUE THREAD

**Issue by BSVogler** [andreasplesch/aframe-meshline-component#1]
I don't see anything but white background and the VR button at the bottom right.

My error log shows 

> tick — aframe.js:68500TypeError: navigator.getGamepads is not a function. (In 'navigator.getGamepads()', 'navigator.getGamepads' is undefined)

**Comment by andreasplesch** [comment]
http://andreasplesch.github.io/aframe-meshline-component/basic/index.html

still works here. The example does not use an aframe.js file, not sure what you are referencing.

**Comment by andreasplesch** [comment]
I see. This example

http://andreasplesch.github.io/aframe-pages/components/meshline

uses the current master/aframe.js which is probably what the error is about.

However, I cannot reproduce on linux FF 38.8 .
