### ISSUE TITLE
line width changes when camera fov changes

### ISSUE THREAD

**Issue by bknill** [andreasplesch/aframe-meshline-component#14]
any way to stop this line changing thickness when the camera zooms?

**Comment by andreasplesch** [comment]
This is a question for the upstream THREE.Meshline helper.

**Comment by bknill** [comment]
Thanks I imagine they'll say use the latest. I tried swapping them out and get a 'getGetUniforms' error. Have you managed to get it running with the latest? 

`three.js:22549 Uncaught TypeError: Cannot read property 'getUniforms' of undefined`

This PR is more upto date as well https://github.com/ryanking1809/threejs-meshline

**Comment by andreasplesch** [comment]
I tried using the latest THREE.Meshline a bit but ran into problems with BufferGeometry. The meshline created THREE.geometry is not instanceof THREE.BufferGeometry (nor instanceof THREE.Geometry) for some reason and three.js complains. I think your issue is related:

https://github.com/spite/THREE.MeshLine/issues/94

**Comment by andreasplesch** [comment]
The problem was that now THREE.Meshline requires its own three. Using the aframe three, I am getting now the same uniforms error.

**Comment by andreasplesch** [comment]
Ok, I managed to update to the latest aframe and meshline. I added the meshline [sizeAttenuation](https://github.com/spite/THREE.MeshLine#create-a-meshlinematerial) option which seemed related. The option is not documented here yet since it requires testing.

**Comment by bknill** [comment]
I fixed it by updating the resolution with the zoom factor,

i.e. on a zoom event I dispatch from my mouse-zoom component, I do the update:
```
  if(e.type == 'zoom')
     this.resolution.set( canvas.width/e.detail,  canvas.height/e.detail );
  else
     this.resolution.set( canvas.width,  canvas.height );
```
