### ISSUE TITLE
Error message found in "https://jsitor.com/SzH16a7KC?html&result" or "Browser Installation" in  github README.md

### ISSUE THREAD

**Issue by richardcck** [andreasplesch/aframe-meshline-component#16]
Dear all

in "https://jsitor.com/SzH16a7KC?html&result" or "Browser Installation" in  "https://github.com/andreasplesch/aframe-meshline-component/blob/master/README.md"

I found below error message, is it normal? How can I fixed it?

"A-Frame:warn Put the A-Frame
A-Frame Version: 0.9.2 (Date 2019-05-06, Commit #f57a1fa)
three Version (https://github.com/supermedium/three.js):
^0.102.2
WebVR Polyfill Version:
^0.10.10
THREE.WebGLRenderer
103dev
core:a-node:error Failure loading node:
{ this.geometry.setAttribute is not a function }
core:a-node:error Failure loading node:
{ this.geometry.setAttribute is not a function }
core:a-node:error Failure loading node:
{ this.geometry.setAttribute is not a function }
Script error."

**Comment by andreasplesch** [comment]
The component works only with newer A-Frame. Try A-Frame 1.0.4:
https://jsitor.com/0pQRYCK2E

**Comment by richardcck** [comment]
thank for prompt reply, and it work properly

**Comment by richardcck** [comment]
thank
