### ISSUE TITLE
Multiple instances of THREE imported

### ISSUE THREAD

**Issue by davidfstein** [andreasplesch/aframe-meshline-component#19]
Receiving this error when loading the component. Can the THREE import be removed from this package and instead rely on the THREE imported with AFRAME?

**Comment by andreasplesch** [comment]
The Meshline lib. required THREE if it was not available. Apparently AFRAME now only exports AFRAME.THREE. I made a small change to just rely on that. Could you please try the latest in the master branch ? If it works for you I can push it to npm. Thanks.

**Comment by andreasplesch** [comment]
Any luck ?

**Comment by davidfstein** [comment]
Hi thanks for your response and sorry for the slow reply. I will test this out tonight and update with the results

**Comment by davidfstein** [comment]
Just checked out master and gave it a shot. Looks like the multiple three import warning is no longer showing up.

**Comment by andreasplesch** [comment]
Thanks, I published the new version on npm.
