### ISSUE TITLE
Does not work as intended?

### ISSUE THREAD

**Issue by BSVogler** [andreasplesch/aframe-meshline-component#2]
Hi!

I wanted to replace the tutorial line with this but my line is reduced to the default one:

![bildschirmfoto 2016-07-23 um 17 19 39](https://cloud.githubusercontent.com/assets/801818/17078684/a585b984-50f9-11e6-90b6-e89ec0b070b6.png)

previously I added many THREE vector3 to the path attribute.

I also noticed that my log is spammed with lines by the component. It would be nice if this could be removed.

**Comment by andreasplesch** [comment]
This is unfortunately not very helpful. Please be more specific.
