### ISSUE TITLE
Remove console.logs in component

### ISSUE THREAD

**Issue by mattrei** [andreasplesch/aframe-meshline-component#4]
Hi,

I like your component, because Spite's Meshlines look much better. However you do have some console.logs in your component, that is a bit noisy while developing for Aframe. May you uncomment them and update the plugin?

Thx,
Matthias

**Comment by andreasplesch** [comment]
This was more of a practice aframe component, so I left those. Good to know that it apparently still works. Simply remove (or comment out) the console.log lines in your aframe-meshline-component.js copy. You can probably even do that in the minified version. I also accept PRs ;)

**Comment by andreasplesch** [comment]
utopiah provided the patch
