### ISSUE TITLE
any reason you used ConstantSpline instead of Curve?

### ISSUE THREAD

**Issue by morandd** [andreasplesch/aframe-meshline-component#7]
In the demo you use the three.ConstantSpline plugin get interpolate the curve into linear segments, but I believe THREE.Curve.getSpacedPoints provides the same thing. May I ask if there's a particular reason you used the plugin rather than the inbuilt Three functionality?

I ask just because I am thinking about using this meshline component to add <path> support for SVG files at https://github.com/7dir/aframe-svgfile-component

If there's a particular reason you did it that way, it would be good to know before embarking on this :)

**Comment by andreasplesch** [comment]
This is a question for

https://github.com/spite/THREE.MeshLine

as this repo is just the aframe interface.
