### ISSUE TITLE
feature request: support curves ("C") in paths

### ISSUE THREAD

**Issue by morandd** [andreasplesch/aframe-meshline-component#8]
currently the path must be composed of linear segments. Would be great to support curves, using SVG curve syntax. This can be done by parsing the SVG path, identifying "C" curves, creating them as Three.CubicBezierCurves, then using Three.Curve.getSpacedPoints to interpolate into linear segments.

**Comment by andreasplesch** [comment]
https://github.com/spite/THREE.MeshLine/blob/master/demo/js/main-svg.js
It would be possible to reuse this to allow for svg paths in a meshlinesvg component. May be pretty straightforward ?

**Comment by morandd** [comment]
done; see my PR.
